server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=api/users/**
            - Path=api/roles/**
        - id: attention-service
          uri: lb://attention-service
          predicates:
            - Path=api/attentions/**
            - Path=api/scores/**
            - Path=api/user-attentions/**
            - Path=api/categories/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=api/reservations/**
            - Path=api/locations/**