server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
            - Path=/roles/**
        - id: attention-service
          uri: lb://attention-service
          predicates:
            - Path=/attentions/**
            - Path=/scores/**
            - Path=/user-attentions/**
            - Path=/categories/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservations/**
            - Path=/locations/**