server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=api/v1/users/**
            - Path=api/v1/roles/**
        - id: attention-service
          uri: lb://attention-service
          predicates:
            - Path=api/v1/attentions/**
            - Path=api/v1/scores/**
            - Path=api/v1/user-attentions/**
            - Path=api/v1/categories/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=api/v1/reservations/**
            - Path=api/v1/locations/**