#Application Configuration
server:
  port: 8096
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8093/h2-console
# Enabling H2 Console
spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost/reservationsdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
    initialization-mode: always

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
# Feign and Hystrix
Feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
